"""Add is_active to Member

Revision ID: 286a35627aba
Revises: ff8d7f219ad8
Create Date: 2026-07-12 21:59:36.430099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286a35627aba'
down_revision: Union[str, Sequence[str], None] = 'ff8d7f219ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute("UPDATE members SET is_active = true")
    op.alter_column('members', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_active')
    # ### end Alembic commands ###
