name: CD (Continuous Delivery)

on:
  push:
    branches:
      - main
      - '*staging*'
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/app || git clone https://github.com/Muzammal-Saleem/Library-Management-System.git ~/app
            cd ~/app
            git pull origin ${{ github.ref_name }}

            cat <<EOF > .env
            POSTGRES_DB=${{ secrets.DB_NAME }}
            POSTGRES_USER=${{ secrets.DB_USER }}
            POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=db
            DB_PORT=5432
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            EOF

            docker compose up -d --build
            docker compose run --rm app alembic upgrade head
            docker compose run --rm app python -m app.seed

